"""ctl.conf rendering and the export table."""

import dataclasses
import os
import re
import tempfile

from oslo_concurrency import lockutils
from oslo_log import log as logging

LOG = logging.getLogger(__name__)

# root ctld parses the file, so a value failing these is refused, not escaped
VOLUME_NAME_RE = re.compile(r'^volume-[0-9a-f-]{36}$')
IQN_RE = re.compile(r'^[A-Za-z0-9.:-]+$')
CHAP_RE = re.compile(r'^[A-Za-z0-9_.-]+$')
DEVICE_PATH_RE = re.compile(r'^/dev/zvol/[A-Za-z0-9/_.-]+$')
LISTEN_RE = re.compile(r'^[A-Za-z0-9.\[\]:-]+:[0-9]+$')

PORTAL_GROUP = 'cinder'
CTLD_PIDFILE = '/var/run/ctld.pid'


def checked(value, pattern, what):
    """Return the value if it matches the pattern."""
    if value is None or not pattern.match(value):
        raise ValueError(f'refusing to render {what} {value!r} into ctl.conf')
    return value


@dataclasses.dataclass(frozen=True)
class Export:
    """One volume exported as an iSCSI target with a single LUN."""

    volume_name: str
    iqn: str
    device_path: str
    chap_username: str | None = None
    chap_password: str | None = None

    def __post_init__(self):
        """Validate every field against its pattern."""
        checked(self.volume_name, VOLUME_NAME_RE, 'volume name')
        checked(self.iqn, IQN_RE, 'target IQN')
        checked(self.device_path, DEVICE_PATH_RE, 'device path')
        if (self.chap_username is None) != (self.chap_password is None):
            raise ValueError('CHAP username and password go together')
        if self.chap_username is not None:
            checked(self.chap_username, CHAP_RE, 'CHAP username')
            checked(self.chap_password, CHAP_RE, 'CHAP password')


def render(exports, listen):
    """Return the complete ctl.conf text for these exports, sorted by IQN."""
    checked(listen, LISTEN_RE, 'listen address')
    lines = [
        '# Generated by cinder-zfs-driver; do not edit. Exports are',
        '# rebuilt from the cinder database on every change.',
        '',
        f'portal-group "{PORTAL_GROUP}" {{',
        '    discovery-auth-group no-authentication',
        f'    listen {listen}',
        '}',
    ]
    for export in sorted(exports, key=lambda e: e.iqn):
        lines += ['', f'target "{export.iqn}" {{']
        if export.chap_username is not None:
            lines.append(
                f'    chap "{export.chap_username}" "{export.chap_password}"'
            )
        else:
            lines.append('    auth-group no-authentication')
        lines += [
            f'    portal-group "{PORTAL_GROUP}"',
            f'    lun 0 {{ path "{export.device_path}" }}',
            '}',
        ]
    return '\n'.join(lines) + '\n'


class CtlTable:
    """The set of current exports, mirrored to a config file and to ctld."""

    def __init__(self, path, listen, reload):
        """Record the config path, listen address and reload callable."""
        self._path = path
        self._listen = listen
        self._reload = reload
        self._exports = {}

    @lockutils.synchronized('cinder-zfs-ctl')
    def add(self, export):
        """Publish an export."""
        self._exports[export.volume_name] = export
        self._sync()

    @lockutils.synchronized('cinder-zfs-ctl')
    def remove(self, volume_name):
        """Withdraw an export."""
        self._exports.pop(volume_name, None)
        self._sync()

    def _sync(self):
        """Rewrite the file and reload ctld if the content changed."""
        text = render(self._exports.values(), self._listen)
        try:
            with open(self._path) as handle:
                if handle.read() == text:
                    return
        except OSError:
            pass
        directory = os.path.dirname(self._path)
        handle, staged = tempfile.mkstemp(dir=directory, prefix='.ctl.conf.')
        try:
            with os.fdopen(handle, 'w') as f:
                f.write(text)
            os.chmod(staged, 0o640)
            os.rename(staged, self._path)
        except OSError:
            try:
                os.unlink(staged)
            except OSError:
                pass
            raise
        LOG.info(
            'wrote %(count)d export(s) to %(path)s',
            {'count': len(self._exports), 'path': self._path},
        )
        self._reload()
